<?xml version="1.0"?>
<robot name="my_mobile_manipulator" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="base_length" value="0.24"/>
  <xacro:property name="base_width" value="0.16"/>
  <xacro:property name="base_height" value="0.08"/>
  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheel_separation" value="0.19"/>
  <xacro:property name="arm_link_len" value="0.15"/> 
  <xacro:property name="arm_link_3_len" value="0.12"/>

  <xacro:macro name="cylinder_inertial" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}"/>
    </inertial>
  </xacro:macro>
  <xacro:macro name="box_inertial" params="m x y z">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0" iyy="${m*(x*x+z*z)/12}" iyz="0" izz="${m*(x*x+y*y)/12}"/>
    </inertial>
  </xacro:macro>
  <xacro:macro name="sphere_inertial" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0" iyy="${2*m*r*r/5}" iyz="0" izz="${2*m*r*r/5}"/>
    </inertial>
  </xacro:macro>

  <material name="blue"><color rgba="0 0 0.8 1"/></material>
  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="white"><color rgba="1 1 1 1"/></material>
  <material name="grey"><color rgba="0.5 0.5 0.5 1"/></material>
  <material name="red"><color rgba="0.8 0 0 1"/></material>
  <material name="green"><color rgba="0 0.8 0 1"/></material>
  <material name="yellow"><color rgba="0.8 0.8 0 1"/></material>
  <material name="cyan"><color rgba="0 0.8 0.8 1"/></material>
  <material name="magenta"><color rgba="0.8 0 0.8 1"/></material>
  <material name="orange"><color rgba="1.0 0.5 0 1"/></material>

  <link name="base_footprint"/>
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius + 0.005}" rpy="0 0 0"/>
  </joint>
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${base_height}" radius="${base_length/2}"/></geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${base_height}" radius="${base_length/2}"/></geometry>
    </collision>
    <xacro:cylinder_inertial m="2.0" r="${base_length/2}" h="${base_height}"/>
  </link>

  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      </collision>
      <xacro:cylinder_inertial m="0.2" r="${wheel_radius}" h="${wheel_width}"/>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 ${reflect*wheel_separation/2} ${wheel_radius*0.5}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>
  <xacro:wheel prefix="left" reflect="1"/>
  <xacro:wheel prefix="right" reflect="-1"/>

  <link name="front_caster">
    <visual><geometry><sphere radius="0.015"/></geometry><material name="white"/></visual>
    <collision><geometry><sphere radius="0.015"/></geometry></collision>
    <xacro:sphere_inertial m="0.05" r="0.015"/>
  </link>
  <joint name="front_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${base_length/2 - 0.02} 0 0" rpy="0 0 0"/>
  </joint>
  <gazebo reference="front_caster"><mu1>0.001</mu1><mu2>0.001</mu2><material>Gazebo/White</material></gazebo>

  <link name="back_caster">
    <visual><geometry><sphere radius="0.015"/></geometry><material name="white"/></visual>
    <collision><geometry><sphere radius="0.015"/></geometry></collision>
    <xacro:sphere_inertial m="0.05" r="0.015"/>
  </link>
  <joint name="back_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="back_caster"/>
    <origin xyz="-${base_length/2 - 0.02} 0 0" rpy="0 0 0"/>
  </joint>
  <gazebo reference="back_caster"><mu1>0.001</mu1><mu2>0.001</mu2><material>Gazebo/White</material></gazebo>

  <link name="arm_base_link">
    <visual><geometry><cylinder radius="0.03" length="0.04"/></geometry><material name="red"/></visual>
    <collision><geometry><cylinder radius="0.03" length="0.04"/></geometry></collision>
    <xacro:cylinder_inertial m="0.2" r="0.03" h="0.04"/>
  </link>
  <joint name="arm_joint_1" type="revolute">
    <parent link="base_link"/>
    <child link="arm_base_link"/>
    <origin xyz="0.05 0 ${base_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1.57" upper="1.57" effort="5.0" velocity="1.0"/>
  </joint>

  <link name="arm_link_1">
    <visual><origin xyz="0 0 ${arm_link_len/2}"/><geometry><box size="0.02 0.02 ${arm_link_len}"/></geometry><material name="green"/></visual>
    <collision><origin xyz="0 0 ${arm_link_len/2}"/><geometry><box size="0.02 0.02 ${arm_link_len}"/></geometry></collision>
    <xacro:box_inertial m="0.1" x="0.02" y="0.02" z="${arm_link_len}"/>
  </link>
  <joint name="arm_joint_2" type="revolute">
    <parent link="arm_base_link"/>
    <child link="arm_link_1"/>
    <origin xyz="0 0 0.02" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="5.0" velocity="1.0"/>
  </joint>

  <link name="arm_link_2">
    <visual><origin xyz="0 0 ${arm_link_len/2}"/><geometry><box size="0.02 0.02 ${arm_link_len}"/></geometry><material name="yellow"/></visual>
    <collision><origin xyz="0 0 ${arm_link_len/2}"/><geometry><box size="0.02 0.02 ${arm_link_len}"/></geometry></collision>
    <xacro:box_inertial m="0.1" x="0.02" y="0.02" z="${arm_link_len}"/>
  </link>
  <joint name="arm_joint_3" type="revolute">
    <parent link="arm_link_1"/>
    <child link="arm_link_2"/>
    <origin xyz="0 0 ${arm_link_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.0" upper="2.0" effort="5.0" velocity="1.0"/>
  </joint>

  <link name="arm_link_3">
    <visual><origin xyz="0 0 ${arm_link_3_len/2}"/><geometry><box size="0.02 0.02 ${arm_link_3_len}"/></geometry><material name="cyan"/></visual>
    <collision><origin xyz="0 0 ${arm_link_3_len/2}"/><geometry><box size="0.02 0.02 ${arm_link_3_len}"/></geometry></collision>
    <xacro:box_inertial m="0.05" x="0.02" y="0.02" z="${arm_link_3_len}"/>
  </link>
  <joint name="arm_joint_4" type="revolute">
    <parent link="arm_link_2"/>
    <child link="arm_link_3"/>
    <origin xyz="0 0 ${arm_link_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="5.0" velocity="1.0"/>
  </joint>

  <link name="gripper_base_link">
    <visual><geometry><box size="0.02 0.10 0.03"/></geometry><material name="magenta"/></visual>
    <collision><geometry><box size="0.02 0.10 0.03"/></geometry></collision>
    <xacro:box_inertial m="0.1" x="0.02" y="0.10" z="0.03"/>
  </link>
  <joint name="gripper_base_joint" type="fixed">
    <parent link="arm_link_3"/>
    <child link="gripper_base_link"/>
    <origin xyz="0 0 ${arm_link_3_len + 0.01}" rpy="0 0 0"/>
  </joint>

  <link name="gripper_left_finger">
    <visual><origin xyz="0 0 0.03"/><geometry><box size="0.02 0.01 0.06"/></geometry><material name="grey"/></visual>
    <collision><origin xyz="0 0 0.03"/><geometry><box size="0.02 0.01 0.06"/></geometry></collision>
    <xacro:box_inertial m="0.05" x="0.02" y="0.01" z="0.06"/>
  </link>
  <joint name="finger_joint_1" type="prismatic">
    <parent link="gripper_base_link"/>
    <child link="gripper_left_finger"/>
    <origin xyz="0 0.04 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.04" upper="0.0" effort="10.0" velocity="0.5"/> 
  </joint>

  <link name="gripper_right_finger">
    <visual><origin xyz="0 0 0.03"/><geometry><box size="0.02 0.01 0.06"/></geometry><material name="grey"/></visual>
    <collision><origin xyz="0 0 0.03"/><geometry><box size="0.02 0.01 0.06"/></geometry></collision>
    <xacro:box_inertial m="0.05" x="0.02" y="0.01" z="0.06"/>
  </link>
  <joint name="finger_joint_2" type="prismatic">
    <parent link="gripper_base_link"/>
    <child link="gripper_right_finger"/>
    <origin xyz="0 -0.04 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0.0" upper="0.04" effort="10.0" velocity="0.5"/>
  </joint>

  <link name="laser_link">
    <visual><geometry><cylinder radius="0.025" length="0.04"/></geometry><material name="black"/></visual>
    <collision><geometry><cylinder radius="0.025" length="0.04"/></geometry></collision>
    <xacro:cylinder_inertial m="0.1" r="0.025" h="0.04"/>
  </link>
  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_link"/>
    <origin xyz="0 0 ${base_height + 0.02}" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/><joint name="imu_joint" type="fixed"><parent link="base_link"/><child link="imu_link"/><origin xyz="0 0 0"/></joint>

  <link name="camera_link">
    <visual><geometry><box size="0.02 0.08 0.02"/></geometry><material name="orange"/></visual>
    <collision><geometry><box size="0.02 0.08 0.02"/></geometry></collision>
    <xacro:box_inertial m="0.05" x="0.02" y="0.08" z="0.02"/>
  </link>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${base_length/2} 0 ${base_height - 0.02}" rpy="0 0 0"/>
  </joint>
  <link name="camera_depth_frame"/>
  <joint name="camera_optical_joint" type="fixed"><parent link="camera_link"/><child link="camera_depth_frame"/><origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/></joint>

  <gazebo reference="base_link"><material>Gazebo/Blue</material></gazebo>
  <gazebo reference="left_wheel"><material>Gazebo/Black</material></gazebo>
  <gazebo reference="right_wheel"><material>Gazebo/Black</material></gazebo>
  <gazebo reference="arm_base_link"><material>Gazebo/Red</material></gazebo>
  <gazebo reference="arm_link_1"><material>Gazebo/Green</material></gazebo>
  <gazebo reference="arm_link_2"><material>Gazebo/Yellow</material></gazebo>
  <gazebo reference="arm_link_3"><material>Gazebo/Cyan</material></gazebo>
  <gazebo reference="gripper_base_link"><material>Gazebo/Purple</material></gazebo>
  <gazebo reference="gripper_left_finger"><material>Gazebo/Grey</material></gazebo>
  <gazebo reference="gripper_right_finger"><material>Gazebo/Grey</material></gazebo>
  <gazebo reference="laser_link"><material>Gazebo/Black</material></gazebo>
  <gazebo reference="camera_link"><material>Gazebo/Orange</material></gazebo>

  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <ros><namespace>/</namespace></ros>
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
    </plugin>
  </gazebo>

  <gazebo reference="laser_link">
    <sensor name="lidar" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan><horizontal><samples>360</samples><resolution>1</resolution><min_angle>-3.14</min_angle><max_angle>3.14</max_angle></horizontal></scan>
        <range><min>0.12</min><max>3.5</max><resolution>0.015</resolution></range>
      </ray>
      <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
        <ros><remapping>~/out:=scan</remapping></ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo reference="imu_link">
    <gravity>true</gravity>
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <topicName>imu</topicName>
        <bodyName>imu_link</bodyName>
        <updateRateHz>10.0</updateRateHz>
        <gaussianNoise>0.0</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>imu_link</frameName>
        <initialOrientationAsReference>false</initialOrientationAsReference>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo reference="camera_link">
    <sensor name="depth_camera" type="depth">
        <visualize>true</visualize>
        <update_rate>30.0</update_rate>
        <camera name="camera">
            <horizontal_fov>1.047</horizontal_fov>
            <image><width>640</width><height>480</height><format>R8G8B8</format></image>
            <clip><near>0.05</near><far>3</far></clip>
        </camera>
        <plugin name="depth_camera_controller" filename="libgazebo_ros_camera.so">
            <baseline>0.2</baseline>
            <alwaysOn>true</alwaysOn>
            <updateRate>0.0</updateRate>
            <frame_name>camera_depth_frame</frame_name>
            <pointCloudCutoff>0.5</pointCloudCutoff>
            <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
            <hackBaseline>0</hackBaseline>
        </plugin>
    </sensor>
  </gazebo>

  <ros2_control name="GazeboSystem" type="system">
    <hardware><plugin>gazebo_ros2_control/GazeboSystem</plugin></hardware>
    <joint name="arm_joint_1"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="arm_joint_2"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="arm_joint_3"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="arm_joint_4"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="finger_joint_1"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="finger_joint_2"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="left_wheel_joint"><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="right_wheel_joint"><state_interface name="position"/><state_interface name="velocity"/></joint>
  </ros2_control>

  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <parameters>$(find final_assignment_pkg)/config/controllers.yaml</parameters>
    </plugin>
  </gazebo>

  <gazebo reference="gripper_left_finger">
    <mu1>1000.0</mu1><mu2>1000.0</mu2><kp>100000.0</kp><kd>1.0</kd>
    <minDepth>0.001</minDepth><maxVel>0.1</maxVel>
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="gripper_right_finger">
    <mu1>1000.0</mu1><mu2>1000.0</mu2><kp>100000.0</kp><kd>1.0</kd>
    <minDepth>0.001</minDepth><maxVel>0.1</maxVel>
    <material>Gazebo/Grey</material>
  </gazebo>

  </robot>
